### ISSUE TITLE
[Feat] Add ``FromNow()`` Function 

### ISSUE THREAD

**Issue by KiddoV** [gookit/goutil#108]
I would like to have something like this:
https://gist.github.com/davidrleonard/259fe449b1ec13bf7d87cde567ca0fde

``func FromNow(time time.Time) string``

The ``func HowLongAgo(sec int64) string`` is not quite enough expressions.

**Comment by inhere** [comment]
added new func: `timex.FromNow(t time.Time) string`. 

Released on version [v0.6.11](https://github.com/gookit/goutil/releases/tag/v0.6.11)

**Comment by KiddoV** [comment]
That was quick. Thanks!
