### ISSUE TITLE
[Question] Function to Get the Extension by MimeType? 

### ISSUE THREAD

**Issue by KiddoV** [gookit/goutil#110]
I am looking for a function to get extension by mime type, e.g:
```golang
func ExtensionsByType(typ string) string

"application/vnd.ms-excel" => ".xls"
"application/pdf" => ".pdf"
"text/plain" => ".txt"
[...]
```

The function ``func mime.ExtensionsByType(typ string) ([]string, error)`` in "mime" package is not cover enough mime types out there!

Would be nice to cover all in this list :))...
https://www.freeformatter.com/mime-types-list.html

Thanks,

**Comment by inhere** [comment]
hi @KiddoV you can see the project: https://github.com/gabriel-vasile/mimetype
