### ISSUE TITLE
ToBool function from internal

### ISSUE THREAD

**Issue by ip75** [gookit/goutil#146]
**System (please complete the following information):**

 - OS: x86_64 x86_64 x86_64 GNU/Linux
 - GO Version: go version go1.21.4 linux/amd64
 - Pkg Version: `0.6.12`

**Describe the suggestion**

You put function [`ToBool`](https://github.com/gookit/goutil/blob/master/internal/comfunc/convert.go#L17) which gets `any` as an argument to internal directory. I need exactly this function. Not string as input parameter but any. Please take this function out of internal directory that I'll have possibility to use it in project.

**Comment by inhere** [comment]
@ip75 hi, you can use `goutil.ToBool` or `goutil.Bool`:

https://github.com/gookit/goutil/blob/f34c18688fb45a4df467033fd0377db7d8aa4ca5/conv.go#L16-L25

**Comment by ip75** [comment]
super! Great thanks! ))
