### ISSUE TITLE
envutil\info.go:29:9: undefined: sysutil.IsConsole

### ISSUE THREAD

**Issue by ammasum** [gookit/goutil#19]
When trying to run application it's showing this message "envutil\info.go:29:9: undefined: sysutil.IsConsole"

**Comment by inhere** [comment]
please provide pkg version

**Comment by ammasum** [comment]
github.com/gookit/goutil v0.2.3

version is v0.2.3
OS: windows 10 pro 64bit

**Comment by inhere** [comment]
thanks. please upgrade pkg version and try again

**Comment by ammasum** [comment]
Thank you so much.. it's working now
