### ISSUE TITLE
在windows平台下，编译报错

### ISSUE THREAD

**Issue by lightbrotherV** [gookit/goutil#2]
windows平台下，在使用github.com/gookit/color和github.com/gookit/gcli/v2/interact时 ,因为依赖了该包，  报了异常undefined sysutil.IsConsole, sysutil.IsMSys,  sysutil.HasShellEnv，启用了go mod，我尝试删除了所有go mod缓存，并且重新编译，但还是报了上述错误。

----------------------------------------------------------------------------------------------------

查阅了源代码，发现sysutil/sysutil.go文件头部有条  // +build !windows 代码，表示winodws下该文件不会编译，是表示该包只能在非windows下使用吗？

**Comment by inhere** [comment]
好的。 我解决下。

**Comment by inhere** [comment]
@lightbrotherV 几个库都修复，发了新版本。你需要更新下。

**Comment by lightbrotherV** [comment]
> 好的，感谢指出。 我解决下。
> 
> > 本来只是想限制 sysutil.Kill 方法的，我把这单独移出去
> 
> @lightbrotherV 😄 有兴趣可以参与，一起维护这几个库

可以呀。





> @lightbrotherV 几个库都修复，发了新版本。你需要更新下。

好的，感谢。
