### ISSUE TITLE
是否可以添加更多功能(类似hutool)

### ISSUE THREAD

**Issue by xcocean** [gookit/goutil#24]
我用了一下发现没有  string.isEmpty 的判空empty之类功能
原谅我是java出身，半路自学go，习惯于 string.isempty、string.blank

**Comment by inhere** [comment]
@xcocean  欢迎添加更多工具方法，可以直接发PR。
我都是使用时发现缺啥就补上啥

**Comment by inhere** [comment]
加了 `IsBlank` 和其他的一些方法，有好的还可以提下
