### ISSUE TITLE
Go1.18beta1 Generics can be used，What do you think?

### ISSUE THREAD

**Issue by xiaozuo7** [gookit/goutil#34]
Functions  like `Reverse` ...to redo might be better 
[related issue](https://github.com/golang/go/issues/43651)

**Comment by inhere** [comment]
😃  Waiting for the Generics official version to be released :)

**Comment by AnkoGo123** [comment]
i dont want the Generics. it is so difficult to read code

**Comment by pokitpeng** [comment]
Is there any plan to upgrade to go1.18 ?

**Comment by inhere** [comment]
@pokitpeng  do you have any good advice?

**Comment by inhere** [comment]
hi @xiaozuo7 @pokitpeng 

Use new git branch or add new build tag to start upgrade Generics? Which is better?

**Comment by pokitpeng** [comment]
> hi @xiaozuo7 @pokitpeng
> 
> Use new git branch or add new build tag to start upgrade Generics? Which is better?


use new git branch is a good idea. refer to another project https://github.com/duke-git/lancet

**Comment by xiaozuo7** [comment]
@inhere 
I think both. First of all, you need to create a branch for developing generic dependencies, and second, stable versions of that branch should be identified with distinguishable tags.

**Comment by inhere** [comment]
hi @xiaozuo7 @pokitpeng 

Since https://github.com/gookit/goutil/releases/tag/v0.6.0 is require go1.18+ and enable Generics
