### ISSUE TITLE
goutil 有将对象数组，指定对象的某个字段转成该字段数组的方法吗？

### ISSUE THREAD

**Issue by kuunnss** [gookit/goutil#66]
因为是从Java转过来的，习惯于stream一些集合操作，在goutil中找到了Find，FindOrDefault，TakeWhile等方法
想问一下有没有取对象数组每一个对象的某个字段，然后转成数组的方法？
和java的 list.stream.map(Product::getXXX) 相似

**Comment by kuunnss** [comment]
orders := make([]Order, 2)
orders[0] = Order{name: "lisi", age: 18}
orders[1] = Order{name: "wang", age: 24}

**Comment by wenccc** [comment]
func arrayColumn[T any, V any](s []T, callback func(val T) (target V, find bool)) []V {
	res := make([]V, 0)
	for _, v := range s {
		target, find := callback(v)
		if find {
			res = append(res, target)
		}
	}
	return res
}
?

**Comment by inhere** [comment]
thanks @wenccc !

已经新增方法：

https://github.com/gookit/goutil/blob/3f1a328a805f927e31f80b8816118a57100326cd/arrutil/collection_gte118.go#L5-L15


> 下个版本发布

**Comment by inhere** [comment]
已发布 https://github.com/gookit/goutil/releases/tag/v0.6.0
