### ISSUE TITLE
strutil能加个函数吗？判断str是否包含substring，substring可以是slice类型

### ISSUE THREAD

**Issue by gouserdev** [gookit/goutil#67]
strutil能加个函数吗？判断str是否包含substring，substring可以是slice类型
例如: strutil.contains("helloword",[]string{"hello", "world"});

**Comment by inhere** [comment]
可以的，欢迎！！带上单元测试就更棒了

> 我能contribute吗

**Comment by inhere** [comment]
搜了下，有这样的函数的：

https://pkg.go.dev/github.com/gookit/goutil/strutil#HasOneSub

```go
func HasOneSub(s string, subs []string) bool
func HasAllSubs(s string, subs []string) bool
```
